[package]
name = "q_and_a"
version = "0.1.0"
edition = "2021"

[dependencies]
handle-errors = { path = "handle-errors" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.2", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "0.8", features = ["v4"] }
warp = "0.3"
