[package]
name = "mock-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bytes = "1"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
